"""

IN:     "key"       <vector>,<vector>,<vector>,...

OUT:    <vector>    <centroid>,<centroid>,<centroid>,...
        <vector>    <centroid>,<centroid>,<centroid>,...
        <vector>    <centroid>,<centroid>,<centroid>,...
        ...
"""
